"""Prompt templates for the EdgeCraft agent."""
from .system import (
    SYSTEM_PROMPT,
    PROPOSAL_GENERATOR_PROMPT,
    REFLECTOR_DIAGNOSIS_PROMPT,
    MODALITY_DETECTION_PROMPT,
    USER_SPEC_PARSING_PROMPT,
    DATASET_ANALYSIS_PROMPT,
    DATASET_EXPLORATION_SYSTEM_PROMPT,
    DATASET_JSON_FROM_REPORT_PROMPT,
)

__all__ = [
    "SYSTEM_PROMPT",
    "PROPOSAL_GENERATOR_PROMPT",
    "REFLECTOR_DIAGNOSIS_PROMPT",
    "MODALITY_DETECTION_PROMPT",
    "USER_SPEC_PARSING_PROMPT",
    "DATASET_ANALYSIS_PROMPT",
    "DATASET_EXPLORATION_SYSTEM_PROMPT",
    "DATASET_JSON_FROM_REPORT_PROMPT",
]
