"""Unified metric normalization and lookup for agent pipeline.

Design goals:
- Keep metric naming flexible in generated scripts (aliases accepted).
- Keep scorer logic canonical (stable metric IDs from UserSpec).
- Be extensible without scattering hardcoded aliases across nodes.
"""
from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Any, Dict, Iterable, Optional, Set, Tuple


@dataclass(frozen=True)
class MetricSpec:
    canonical: str
    aliases: Tuple[str, ...]
    category: str  # "train" | "edge" | "generic"


class MetricRegistry:
    """Registry of canonical metric names and aliases."""

    _specs: Dict[str, MetricSpec] = {}
    _alias_to_canonical: Dict[str, str] = {}
    _initialized = False
    _positive_measurements = {
        "Latency",
        "Latency_mean",
        "Latency_p50",
        "Latency_p95",
        "Latency_p99",
        "Memory_mb",
        "Throughput",
        "Power_w",
        "Energy_j",
        "Energy_mj",
    }

    @classmethod
    def register(cls, canonical: str, aliases: Iterable[str], category: str = "generic") -> None:
        canonical = canonical.strip()
        alias_tuple = tuple(a.strip() for a in aliases if a and a.strip())
        cls._specs[canonical] = MetricSpec(canonical=canonical, aliases=alias_tuple, category=category)
        # canonical itself should resolve as well
        cls._alias_to_canonical[canonical.lower()] = canonical
        for alias in alias_tuple:
            cls._alias_to_canonical[alias.lower()] = canonical

    @classmethod
    def ensure_defaults(cls) -> None:
        if cls._initialized:
            return
        cls._initialized = True

        # Train-side quality metrics (vision defaults + common names)
        # NOTE: LLMs often generate wrong key variants (underscores, missing parens).
        # All observed variants from real runs are listed here as aliases.
        cls.register("mAP", [
            "map",
            "metrics/mAP50-95(B)", "metrics/mAP50-95", "metrics/map50-95",
            # underscore variants generated by LLMs
            "metrics/mAP_50-95", "metrics/mAP_50_95", "metrics/map_50_95",
            # box_map from DetMetrics.results_dict
            "box_map", "box_mAP",
            # bare names
            "mAP50-95", "mAP_50-95",
        ], "train")
        cls.register("mAP50", [
            "map50",
            "metrics/mAP50(B)", "metrics/mAP50", "metrics/map50",
            # underscore variants
            "metrics/mAP_50", "metrics/map_50",
            # box_map50 from DetMetrics
            "box_map50", "box_mAP50",
            # bare names
            "mAP_50",
        ], "train")
        cls.register("Precision", ["precision", "metrics/precision(B)", "metrics/precision"], "train")
        cls.register("Recall", ["recall", "metrics/recall(B)", "metrics/recall"], "train")
        cls.register("F1Score", ["f1", "f1score"], "train")
        cls.register("Accuracy", ["accuracy", "acc", "top1", "top1_acc"], "train")
        cls.register("AUC", ["auc", "auroc"], "train")
        cls.register("mIoU", [
            "miou", "mean_iou", "meanIoU",
            "mask_miou", "mask_iou",
            "metrics/mIoU", "metrics/miou",
            "metrics/mAP50-95(M)", "metrics/mAP50(M)",
            "seg_map", "mask_map", "mask_mAP",
        ], "train")
        cls.register("WER", ["wer", "word_error_rate"], "train")
        cls.register("MAE", ["mae"], "train")
        cls.register("RMSE", ["rmse"], "train")

        # Edge-side deployment metrics
        cls.register("Latency", ["latency_ms", "latency_avg_ms", "inference_time_ms", "Latency_ms"], "edge")
        cls.register("Latency_mean", ["latency_mean_ms"], "edge")
        cls.register(
            "Latency_p50",
            ["latency_p50", "latency_p50_ms", "p50_latency_ms"],
            "edge",
        )
        cls.register(
            "Latency_p95",
            ["latency_p95", "latency_p95_ms", "p95_latency_ms"],
            "edge",
        )
        cls.register(
            "Latency_p99",
            ["latency_p99", "latency_p99_ms", "p99_latency_ms"],
            "edge",
        )
        cls.register("Memory_mb", ["memory_mb", "MemoryMB", "peak_memory_mb", "memory_used_mb"], "edge")
        cls.register("Throughput", ["throughput_fps", "fps"], "edge")
        cls.register("Power_w", ["power_w", "power"], "edge")
        cls.register(
            "Energy_j",
            [
                "energy_j",
                "energy_j_per_inference",
                "joules_per_inference",
                "joule_per_inference",
            ],
            "edge",
        )
        cls.register(
            "Energy_mj",
            ["energy_mj", "energy_mj_per_inference", "energy", "energy_per_inference_mj"],
            "edge",
        )

    @classmethod
    def canonicalize_name(cls, metric_name: str) -> str:
        cls.ensure_defaults()
        if not metric_name:
            return metric_name
        name = metric_name.strip()
        key = name.lower()
        if key in cls._alias_to_canonical:
            return cls._alias_to_canonical[key]
        for prefix in ("eval_", "val_", "valid_", "validation_", "test_"):
            if key.startswith(prefix):
                stripped = key[len(prefix):]
                if stripped in cls._alias_to_canonical:
                    return cls._alias_to_canonical[stripped]
        return name

    @classmethod
    def normalize_metric_dict(cls, metrics: Dict[str, object]) -> Dict[str, float]:
        """Normalize raw metric payload into canonical names with float values.

        Unknown metrics are preserved as-is when numeric.
        """
        cls.ensure_defaults()
        out: Dict[str, float] = {}
        for k, v in (metrics or {}).items():
            if isinstance(v, (int, float)):
                canonical = cls.canonicalize_name(str(k))
                if not cls.is_valid_measurement(canonical, float(v)):
                    continue
                # Keep first value for a canonical metric to avoid unstable overwrite order.
                if canonical not in out:
                    out[canonical] = float(v)
        # The paper's unqualified latency SLO is defined over warm-up-adjusted
        # p95. Preserve the arithmetic mean as diagnostics, but make the p95
        # value authoritative whenever the evaluator reports both.
        if "Latency" in out:
            out.setdefault("Latency_mean", out["Latency"])
        if "Latency_p95" in out:
            out["Latency"] = out["Latency_p95"]
        return out

    @classmethod
    def is_valid_measurement(cls, metric_name: str, value: object) -> bool:
        """Return whether a numeric metric is credible measurement evidence.

        Runtime scripts commonly use ``-1`` or ``0`` as an unavailable-value
        sentinel.  Resource measurements are physical quantities, so those
        sentinels must remain unknown rather than becoming excellent scores.
        """
        cls.ensure_defaults()
        if not isinstance(value, (int, float)) or not math.isfinite(float(value)):
            return False
        canonical = cls.canonicalize_name(metric_name)
        return canonical not in cls._positive_measurements or float(value) > 0.0

    @classmethod
    def lookup_value(cls, query_metric: str, metrics: Optional[Dict[str, float]]) -> Optional[float]:
        cls.ensure_defaults()
        if not metrics:
            return None
        # exact first
        if query_metric in metrics:
            return metrics[query_metric]
        # canonicalized query
        canonical = cls.canonicalize_name(query_metric)
        if canonical in metrics:
            return metrics[canonical]
        # query may be alias while dict keeps canonical or vice versa
        for key, value in metrics.items():
            if cls.canonicalize_name(key) == canonical:
                return value
        return None

    @classmethod
    def is_edge_metric(cls, metric_name: str) -> bool:
        cls.ensure_defaults()
        canonical = cls.canonicalize_name(metric_name)
        spec = cls._specs.get(canonical)
        return bool(spec and spec.category == "edge")


def lookup_trial_metric(
    metric_name: str,
    local_metrics: Any,
    edge_metrics: Any,
) -> Optional[float]:
    """Read one metric with the same ownership semantics across the agent.

    Quality is owned by local validation when present, with measured edge
    quality as a fallback. Deployment metrics are owned by the edge result.
    """
    local_pool = dict(getattr(local_metrics, "all_metrics", {}) or {})
    edge_pool = dict(getattr(edge_metrics, "all_metrics", {}) or {})
    if edge_metrics is not None:
        runtime_used = str(getattr(edge_metrics, "runtime_used", "") or "").strip().lower()
        if runtime_used == "surrogate":
            edge_pool = {}
        latency = getattr(edge_metrics, "latency_ms", None)
        latency_p95 = getattr(edge_metrics, "latency_p95_ms", None)
        latency_mean = getattr(edge_metrics, "latency_mean_ms", None)
        memory = getattr(edge_metrics, "memory_mb", None)
        throughput = getattr(edge_metrics, "throughput_fps", None)
        if latency_mean is not None and runtime_used != "surrogate":
            edge_pool.setdefault("Latency_mean", latency_mean)
        if latency_p95 is not None and runtime_used != "surrogate":
            edge_pool["Latency_p95"] = latency_p95
            edge_pool["Latency"] = latency_p95
        elif latency is not None and runtime_used != "surrogate":
            edge_pool.setdefault("Latency", latency)
        if memory is not None and runtime_used != "surrogate":
            edge_pool.setdefault("Memory_mb", memory)
        if throughput is not None and runtime_used != "surrogate":
            edge_pool.setdefault("Throughput", throughput)

    # Device monitors historically report millijoules while formal intents use
    # joules_per_inference. Keep both canonical units available at this single
    # ownership boundary instead of scattering conversions through scorers.
    energy_mj = MetricRegistry.lookup_value("Energy_mj", edge_pool)
    energy_j = MetricRegistry.lookup_value("Energy_j", edge_pool)
    if energy_j is None and energy_mj is not None:
        edge_pool["Energy_j"] = float(energy_mj) / 1000.0
    elif energy_mj is None and energy_j is not None:
        edge_pool["Energy_mj"] = float(energy_j) * 1000.0

    local_value = MetricRegistry.lookup_value(metric_name, local_pool)
    edge_value = MetricRegistry.lookup_value(metric_name, edge_pool)
    if local_value is not None and not MetricRegistry.is_valid_measurement(metric_name, local_value):
        local_value = None
    if edge_value is not None and not MetricRegistry.is_valid_measurement(metric_name, edge_value):
        edge_value = None
    if MetricRegistry.is_edge_metric(metric_name):
        return edge_value if edge_value is not None else local_value
    return local_value if local_value is not None else edge_value


def split_required_metrics_for_codegen(
    constraint_metrics: Iterable[str],
    preference_metrics: Iterable[str],
) -> tuple[list[str], list[str]]:
    """Split model-owned metrics from evaluator-owned physical measurements."""
    MetricRegistry.ensure_defaults()
    train: list[str] = []
    infer: list[str] = ["Latency", "Memory_mb"]
    for m in list(constraint_metrics) + list(preference_metrics):
        if not m:
            continue
        canonical = MetricRegistry.canonicalize_name(m)
        if MetricRegistry.is_edge_metric(canonical):
            # Power and energy come from synchronized device sensors. Asking
            # generated code to emit them creates ungrounded zeroes or guesses.
            if canonical not in {"Power_w", "Energy_mj"} and canonical not in infer:
                infer.append(canonical)
        else:
            if canonical not in train:
                train.append(canonical)
    if not train:
        train = ["mAP", "mAP50"]
    return train, infer


# Ultralytics train() results_dict key map (canonical metric -> results_dict key)
_ULTRALYTICS_RESULTS_DICT_KEYS: Dict[str, str] = {
    "mAP": "metrics/mAP50-95(B)",
    "mAP50": "metrics/mAP50(B)",
    "Precision": "metrics/precision(B)",
    "Recall": "metrics/recall(B)",
    "mIoU": "metrics/mAP50-95(M)",
}


def ultralytics_results_dict_key(metric_name: str) -> Optional[str]:
    """Map a metric name (canonical or alias) to ultralytics results_dict key."""
    canonical = MetricRegistry.canonicalize_name(metric_name)
    return _ULTRALYTICS_RESULTS_DICT_KEYS.get(canonical)
